version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: ./php.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html:z
      - ./db:/var/db:z
    command: >
      sh -c "chmod -R 777 /var/db && php-fpm && composer install "

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html:z
      - ./db:/var/db:z
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
    depends_on:
      - php
